# Generated by Django 5.1.3 on 2025-03-11 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_artist_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_composition_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_session_artist_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_session_composition_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='composition',
        ),
        migrations.AddField(
            model_name='artist',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured artists will appear on the home page'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured events will appear on the home page'),
        ),
        migrations.AlterField(
            model_name='like',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='events.artist'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'artist'), name='unique_user_artist_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'artist'), name='unique_session_artist_like'),
        ),
    ]
