# Generated by Django 5.1.3 on 2025-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_like_unique_user_artist_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X URL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps Link'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('local', 'Mahalliy'), ('international', 'Xorijiy')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
