# Generated by Django 5.1.3 on 2025-03-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='map_link',
        ),
    ]
