# Generated by Django 5.1.6 on 2025-03-18 20:06

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20250318_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Madaniyat Vazirligi', max_length=255, verbose_name='Sayt nomi')),
                ('contact_email', models.EmailField(default='info@madaniyat.uz', max_length=254, verbose_name='Aloqa email')),
                ('contact_phone', models.CharField(default='+998 71 123 4567', max_length=100, verbose_name='Telefon raqam')),
                ('contact_address', models.TextField(default='100128, Toshkent, Oʻzbekiston', verbose_name='Manzil')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram URL')),
                ('contact_page_title', models.CharField(default="Biz bilan bog'lanish", max_length=255, verbose_name='Aloqa sahifa sarlavhasi')),
                ('contact_page_description', tinymce.models.HTMLField(blank=True, verbose_name='Aloqa sahifa mazmuni')),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps-dan olingan joylashuv HTML kodi', verbose_name='Google Maps iframe kodi')),
                ('footer_text', models.TextField(blank=True, verbose_name="Footer qo'shimcha matn")),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Sanʼatkor ', 'verbose_name_plural': 'Sanʼatkorlar'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'Kompozitsiya ', 'verbose_name_plural': 'Kompozitsiyalar'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Tadbir ', 'verbose_name_plural': 'Tadbirlar'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like ', 'verbose_name_plural': 'Like lar'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Sanʼatkor tafsilotlari'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Sanʼatkor rasmi'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Sanʼatkor nomi'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='composition',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='events.artist', verbose_name='Sanʼatkor'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='composition_covers/', verbose_name='Kompozitsiya rasmi'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Kompozitsiya tafsilotlari'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='compositions/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube havola'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kompozitsiya nomi'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='type',
            field=models.CharField(choices=[('music', 'Music'), ('video', 'Video')], default='music', max_length=10, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.artist', verbose_name='Sanʼatkorlar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Tadbir sanasi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Tadbir tafsilotlari'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Tadbir rasm'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Xaritada kenglik'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Tadbir manzili'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Xaritada uzunlik'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tadbir nomi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('local', 'Mahalliy'), ('international', 'Xorijiy')], max_length=255, verbose_name='Tadbir turi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='like',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='events.artist', verbose_name='Sanʼatkor'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='like',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Session key'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
