# Generated by Django 5.1.6 on 2025-03-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_sitesettings_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', "Ko'rib chiqilmoqda"), ('completed', 'Bajarildi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Admin izohlari')),
            ],
            options={
                'verbose_name': 'Murojat',
                'verbose_name_plural': 'Murojatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
