# Generated by Django 5.1.6 on 2025-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_murojat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bilet narxi'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, null=True, verbose_name='Bilet sotib olish havolasi'),
        ),
    ]
