services:
  # db:
  #   image: postgres:16
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
  #   env_file:
  #     - .env
  #   restart: always

  web:
    build: .
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8200
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:9001"
    #  gunicorn config.wsgi:application --bind 0.0.0.0:9001"
    volumes:
      - .:/app
    ports:
      - "9001:9001"
    # depends_on:
    #   - db
    restart: always

volumes:
  web: